language: cpp

# compilers to add to build matrix
compiler:
  - gcc

before_install:
# -qq : quiet 
# -y  : yes to all
# install of cppcheck
 - sudo apt-get update -qq
 - sudo apt-get install -y cppcheck
# install of gtest and compilation
 - sudo apt-get install -y libgtest-dev
 - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"

# scripts to run before build
before_script:
  - pwd

# build app, and run tests (ie make & make test)
script:
  - sh travisBuild.sh
